# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RefreshToken(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, refresh_token: str=None):  # noqa: E501
        """RefreshToken - a model defined in Swagger

        :param refresh_token: The refresh_token of this RefreshToken.  # noqa: E501
        :type refresh_token: str
        """
        self.swagger_types = {
            'refresh_token': str
        }

        self.attribute_map = {
            'refresh_token': 'refresh_token'
        }
        self._refresh_token = refresh_token

    @classmethod
    def from_dict(cls, dikt) -> 'RefreshToken':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Refresh_token of this RefreshToken.  # noqa: E501
        :rtype: RefreshToken
        """
        return util.deserialize_model(dikt, cls)

    @property
    def refresh_token(self) -> str:
        """Gets the refresh_token of this RefreshToken.


        :return: The refresh_token of this RefreshToken.
        :rtype: str
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token: str):
        """Sets the refresh_token of this RefreshToken.


        :param refresh_token: The refresh_token of this RefreshToken.
        :type refresh_token: str
        """

        self._refresh_token = refresh_token
