openapi: 3.0.0
info:
    title: Test api
    description: minha api de teste com o swegger
    version: '1.0.0'

servers:
  - url: http://localhost:5000/
    description: localhost

paths:
    /hello:
        get:
            summary: Retorna uma mensagem "hello world"
            description: Rotorna um json contendo uma mensagem de "hello world"
            responses: 
              '200':
                description: mensagem recebida com sucesso
                content: 
                  application/json: 
                    schema: 
                      type: string
    /parametro/{num}:
        get:
            summary: retornam o numero passado
            parameters: 
              - name: num
                in: path
                required: true
                description: um numero qualquer
                schema: 
                  type: integer
                  format: int64
                  minimum: 1
            responses: 
              '200':
                description: OK
    /create:
      post:
        summary: criar um usuário
        description: rota usada para criar usuário
        requestBody: 
          required: true
          content: 
            application/json: 
              schema: 
                type: object
                properties: 
                  username:
                    type: string
                    
              
        responses:
          '201':
            description: o usuário foi criado com sucesso
    /users/{userId}:
      get:
        summary: Returns a user by ID.
        parameters:
          - name: userId
            in: path
            required: true
            description: The ID of the user to return.
            schema:
              type: integer
              format: int64
              minimum: 1
        responses:
          '200':
            description: A user object.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/User'
          '400':
            description: The specified user ID is invalid (not a number).
          '404':
            description: A user with the specified ID was not found.
          default:
            description: Unexpected error 

components:
  schemas:
    User:
      type: object
      properties: 
        username:
          type: string
          example: lukas
        password:
          type: string
          example: 123
      required: 
        - username
        - password