# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SuccessLogin(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, access_token: str=None, refresh_token: str=None):  # noqa: E501
        """SuccessLogin - a model defined in Swagger

        :param access_token: The access_token of this SuccessLogin.  # noqa: E501
        :type access_token: str
        :param refresh_token: The refresh_token of this SuccessLogin.  # noqa: E501
        :type refresh_token: str
        """
        self.swagger_types = {
            'access_token': str,
            'refresh_token': str
        }

        self.attribute_map = {
            'access_token': 'access_token',
            'refresh_token': 'refresh_token'
        }
        self._access_token = access_token
        self._refresh_token = refresh_token

    @classmethod
    def from_dict(cls, dikt) -> 'SuccessLogin':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Success_Login of this SuccessLogin.  # noqa: E501
        :rtype: SuccessLogin
        """
        return util.deserialize_model(dikt, cls)

    @property
    def access_token(self) -> str:
        """Gets the access_token of this SuccessLogin.


        :return: The access_token of this SuccessLogin.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token: str):
        """Sets the access_token of this SuccessLogin.


        :param access_token: The access_token of this SuccessLogin.
        :type access_token: str
        """

        self._access_token = access_token

    @property
    def refresh_token(self) -> str:
        """Gets the refresh_token of this SuccessLogin.


        :return: The refresh_token of this SuccessLogin.
        :rtype: str
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token: str):
        """Sets the refresh_token of this SuccessLogin.


        :param refresh_token: The refresh_token of this SuccessLogin.
        :type refresh_token: str
        """

        self._refresh_token = refresh_token
